import ImagePNG from '../assets/book/image.png';
import ImageSecondPNG from '../assets/book/image-2.png';
import ImageThirdPNG from '../assets/book/image-3.png';
import ImageFourthPNG from '../assets/book/image-4.png';
import ImageFiftthPNG from '../assets/book/image-5.png';

import { reviews } from './reviews';

export const books: any[] = [
  {
    id: '1',
    images: [],
    author: 'Адитья Бхаргава',
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих',
    rating: 0,
    year: 2019,
    book: false,
    dateTaken: '',
    category: 'business',
    reviews,
  },
  {
    id: '2',
    images: [{ id: '1', image: ImagePNG }],
    author: 'Патрик Нимейер, Дэниэл Леук',
    title: 'Программирование на JAVA',
    rating: 4,
    year: 2013,
    book: false,
    dateTaken: '',
    category: 'classic',
    reviews,
  },
  {
    id: '3',
    images: [
      { id: '1', image: ImagePNG },
      { id: '2', image: ImageSecondPNG },
      { id: '3', image: ImageThirdPNG },
      { id: '4', image: ImageFourthPNG },
      { id: '5', image: ImageFiftthPNG },
      { id: '6', image: ImagePNG },
      { id: '7', image: ImageSecondPNG },
      { id: '8', image: ImageThirdPNG },
    ],
    author: 'Адитья Бхаргава',
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих',
    rating: 0,
    year: 2019,
    book: false,
    dateTaken: '23.04',
    category: 'psychology',
    reviews: [],
  },
  {
    id: '4',
    images: [],
    author: 'Патрик Нимейер, Дэниэл Леук',
    title: 'Программирование на JAVA',
    rating: 4,
    year: 2013,
    book: true,
    dateTaken: '',
    category: 'classic',
    reviews,
  },
  {
    id: '5',
    images: [],
    author: 'Адитья Бхаргава',
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих',
    rating: 0,
    year: 2019,
    book: false,
    dateTaken: '',
    category: 'psychology',
    reviews: [],
  },
  {
    id: '6',
    images: [],
    author: 'Патрик Нимейер, Дэниэл Леук',
    title: 'Программирование на JAVA',
    rating: 4,
    year: 2013,
    book: true,
    dateTaken: '',
    category: 'business',
    reviews,
  },
  {
    id: '7',
    images: [],
    author: 'Адитья Бхаргава',
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих',
    rating: 4,
    year: 2019,
    book: false,
    dateTaken: '',
    category: 'business',
    reviews: [],
  },
  {
    id: '8',
    images: [],
    author: 'Патрик Нимейер, Дэниэл Леук',
    title: 'Программирование на JAVA',
    rating: 4,
    year: 2013,
    book: false,
    dateTaken: '25.01',
    category: 'business',
    reviews,
  },
];
