export const library: any[] = [
  {
    id: '1',
    genre: 'Бизнес-книги',
    category: 'business',
    length: 14,
  },
  {
    id: '2',
    genre: 'Детективы',
    category: 'detective',
    length: 8,
  },
  {
    id: '3',
    genre: 'Детские книги',
    category: 'children',
    length: 14,
  },
  {
    id: '4',
    genre: 'Зарубежная литература',
    category: 'foreign',
    length: 2,
  },
  {
    id: '5',
    genre: 'История',
    category: 'history',
    length: 5,
  },
  {
    id: '6',
    genre: 'Классическая литература',
    category: 'classic',
    length: 12,
  },
  {
    id: '7',
    genre: 'Книги по психологии',
    category: 'psychology',
    length: 11,
  },
  {
    id: '8',
    genre: 'Компьютерная литература',
    category: 'computer',
    length: 54,
  },
  {
    id: '9',
    genre: 'Культура и искусство',
    category: 'art',
    length: 5,
  },
  {
    id: '10',
    genre: 'Наука и образование',
    category: 'science',
    length: 2,
  },
  {
    id: '11',
    genre: 'Публицистическая литература',
    category: 'publicistic',
    length: 0,
  },
  {
    id: '12',
    genre: 'Справочники',
    category: 'references',
    length: 10,
  },
  {
    id: '13',
    genre: 'Фантастика',
    category: 'fantasy',
    length: 12,
  },
  {
    id: '14',
    genre: 'Юмористическая литература',
    category: 'humor',
    length: 8,
  },
];
